# .golangci.yml
# The rationale follows this link:
#   https://docs.google.com/spreadsheets/u/0/d/1AOin8xMeChW6XL2fufvyjeXBAclqSZ7P7YCi9SMgYEc/htmlview

linters:
  enable-all: true
  disable:
    - depguard # don't have the whitelist and blacklist
    - exhaustruct # Not a general purpose linter and is suitable to be enabled with specific types that expect all fields to be populated during usage.
    - exportloopref  # Replaced by copyloopvar
    - gochecknoglobals # While the principle is agreeable, it is hard to disallow all global variables.
    - paralleltest # The test code can't be parallelized now
    - wsl # Using gofumpt which addresses whitespace consistency for the most part and this linter admits to being too aggressive.
    - wrapcheck # Always wrapping errors is not necessary and having a linter mandating the same could be too annoying.
    - varnamelen # prefer short variable names
    - funlen # test functions are allowed to be long
    - nlreturn # not mandatory
    - ireturn # can return interface, because too many false positives.
    - recvcheck # use pointer for changes, use value for reads
    - forcetypeassert # handled by errcheck
    - gofmt # gofumpt includes formatting rules that are a superset of gofmt.

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/jambo0624)
    custom-order: true

  errcheck:
    check-type-assertions: true
    
  revive:
    rules:
      - name: indent-error-flow
        disabled: true

  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 150
    # Tab width in spaces.
    # Default: 1
    tab-width: 1

  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 100

  dogsled:
    # Checks assignments with too many blank identifiers.
    # Default: 2
    max-blank-identifiers: 3

issues:
  exclude-rules:
    - path: "(_test\\.go|mock_)"
      text: "^Error return value is not checked$"
      linters: ["errcheck"]
